services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        image: tpqmis
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    # queue:
    #     image: tpqmis
    #     restart: always
    #     depends_on:
    #         - php
    #     volumes:
    #         - .:/var/www
    #     command: php artisan queue:work

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: mysql:8.1
        restart: always
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tpqmis
            MYSQL_USER: tpqmis
            MYSQL_PASSWORD: tpqmis

